/** One entry in the bundled sample library (decision e7xm4p). METADATA only — the CESR bytes are
 *  never compiled into the app; `file` names a static file published under public/samples/ and
 *  fetched on demand (see fetchSample). `file` is relative to the app base URL. */
export interface SampleMeta {
  id: string;
  label: string;
  description: string;
  file: string;
  version: '1' | '2'; // CESR genus — the picker groups the menu by this (decision d4mx9k)
}

/* The curated corpus: the PII-free samples that frame cleanly. The CESR-1 set plus the CESR-2 twins
 * of the two witness OOBIs (same AID, same config, different CESR genus — a deliberate compare-the-
 * genera pair, now that the walker frames v2, q9rd3m). A TEL + ACDC example is a follow-up ~32l6
 * (needs a credential-issuance flow to generate clean data). Provenance: samples/PROVENANCE.md. */
export const SAMPLES: SampleMeta[] = [
  {
    id: 'kel',
    label: 'Key event log',
    description: "A controller's KEL: inception, rotation, then an interaction event.",
    file: 'samples/kel-icp-rot-ixn.cesr',
    version: '1',
  },
  {
    id: 'witness-oobi',
    label: 'Witness OOBI',
    description: "A witness's controller OOBI response — its KEL plus endpoint-authorization replies.",
    file: 'samples/witness-controller-oobi.cesr',
    version: '1',
  },
  {
    id: 'witness-role-oobi',
    label: 'Witness-role OOBI',
    description: 'A witness-role OOBI: the inception event that introduces a witness.',
    file: 'samples/witness-role-oobi.cesr',
    version: '1',
  },
  {
    id: 'witness-oobi-v2',
    label: 'Witness OOBI',
    description: "The same witness's controller OOBI, generated by keri 2.x — CESR-2.0 version strings and attachments.",
    file: 'samples/witness-controller-oobi-v2.cesr',
    version: '2',
  },
  {
    id: 'witness-role-oobi-v2',
    label: 'Witness-role OOBI',
    description: 'The witness-role OOBI in CESR 2.0 — the CESR-1 twin of this same witness is listed above.',
    file: 'samples/witness-role-oobi-v2.cesr',
    version: '2',
  },
];
